// Substitua pelos seus dados do painel Supabase (Settings > API)
const SUPABASE_URL = 'https://wthvlmdoxolosacruosb.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0aHZsbWRveG9sb3NhY3J1b3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyNDEyNDcsImV4cCI6MjEwMDgxNzI0N30.JW3GispsRDpe-2IsxlzbXFmdXquVe_JgLicQqkm-0q4';

const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const TMDB_TOKEN = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5NDk0ODNiZTc0YzM4OGNmNjYxNTZjOTk5YjUxZTAyZCIsIm5iZiI6MTc4NTI0OTA5Ny44NzM5OTk4LCJzdWIiOiI2YTY4YmQ0OTExOTlmZjg5NDJkZWNjOTciLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.1r28YJoj3soJ-nPXeGmNBFbBJ_vaFJSuhO5ASyF1200';